ITEM.name = "Hybrid Item"
ITEM.description = "Hybrid item with armor, backpack, and bag functionality"
ITEM.longdesc = "A bandit variant of the Hawk suit, the suit has seen considerable modification to fit the needs of camp raiders and thugs.   .\n\nBallistic Protection:\nSkull: II\nNeck & Face: 0\nTorso: IIIA\nLimbs: II\nWeight: 1"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 1
ITEM.flag = "A"
ITEM.br = 0.2
ITEM.fbr = 8
ITEM.ar = 0.05
ITEM.far = 1.5
ITEM.isGasmask = true
ITEM.isArmor = true
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.category = "backpack"
ITEM.isArmor = true
ITEM.isBackpack = true
ITEM.isBag = true
ITEM.invWidth = 4
ITEM.invHeight = 3
ITEM.artifactcontainers = {"0"}
ITEM.weight = 5
ITEM.maxArmor = 10
ITEM.res = {
	["Fall"] = 0,
	["Blast"] = 0,
	["Bullet"] = 0,
	["Shock"] = 0,
	["Burn"] = 0,
	["Radiation"] = 0,
	["Psi"] = 0,
}
ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}