ITEM.name = "\"Black\" Hawk"
ITEM.model ="models/kek1ch/merc_outfit.mdl"
ITEM.description= "A bandit twist on the standard mercenary suit."
ITEM.longdesc = "A bandit variant of the Hawk suit, the suit has seen considerable modification to fit the needs of camp raiders and thugs.   .\n\nBallistic Protection:\nSkull: II\nNeck & Face: 0\nTorso: IIIA\nLimbs: II\nWeight: 1"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 36000
ITEM.flag = "A"
ITEM.br = 0.2
ITEM.fbr = 8
ITEM.ar = 0.05
ITEM.far = 1.5
ITEM.isGasmask = true
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.artifactcontainers = {"0"}
ITEM.weight = 5
ITEM.maxArmor = 10
ITEM.res = {
	["Bullet"] = 0.3,
	["Blast"] = 0.3,
	["Fall"] = 0.3,
	["Burn"] = 0,
	["Radiation"] = 0.2,
	["Chemical"] = 0.1,
	["Shock"] = 0,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}
ITEM.pacData = { [1] = {
	["children"] = {
		[1] = {
			["children"] = {
				[1] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["InvertHideMesh"] = false,
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "head",
						["ScaleChildren"] = false,
						["UniqueID"] = "7a028ec633da97b4921f4937cd656a3d80b7871bad843bcb54e902eee44a7023",
						["MoveChildrenToOrigin"] = false,
						["Position"] = Vector(2.6291999816895, 0.55940002202988, 0),
						["AimPartUID"] = "",
						["Angles"] = Angle(0, 0, 0),
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["ClassName"] = "bone3",
						["Size"] = 1,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[2] = {
					["children"] = {
					},
					["self"] = {
						["DrawOrder"] = 0,
						["UniqueID"] = "cd54038344a1ee587427965f2ae0decd14bcfcfabb0602b02c59ba8eccef4f6a",
						["Hide"] = false,
						["TargetEntityUID"] = "",
						["EditorExpand"] = false,
						["Name"] = "",
						["Material"] = "pp/frame_blend",
						["IsDisturbing"] = false,
						["SubMaterialId"] = 5,
						["ClassName"] = "submaterial",
						["RootOwner"] = false,
					},
				},
				[3] = {
					["children"] = {
					},
					["self"] = {
						["DrawOrder"] = 0,
						["UniqueID"] = "bbd245892f4520702922c7af04e7e6a3c03e45d7cbfc1232971ff9f124c05fed",
						["Hide"] = false,
						["TargetEntityUID"] = "",
						["EditorExpand"] = false,
						["Name"] = "",
						["Material"] = "pp/frame_blend",
						["IsDisturbing"] = false,
						["SubMaterialId"] = 4,
						["ClassName"] = "submaterial",
						["RootOwner"] = false,
					},
				},
				[4] = {
					["children"] = {
					},
					["self"] = {
						["DrawOrder"] = 0,
						["UniqueID"] = "e1578229d0212f0950eb20484f48baee60da81ad72b2c517c81948d69e23a34c",
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["Bone"] = "head",
						["BlendMode"] = "",
						["Position"] = Vector(2.602294921875, -1.1123046875, 0.421142578125),
						["AimPartUID"] = "",
						["NoTextureFiltering"] = false,
						["Hide"] = false,
						["Name"] = "",
						["Translucent"] = false,
						["IgnoreZ"] = false,
						["Angles"] = Angle(0.80031788349152, -164.42007446289, -178.42370605469),
						["AngleOffset"] = Angle(0, 0, 0),
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["ClassName"] = "clip2",
						["EyeAngles"] = false,
						["EditorExpand"] = false,
					},
				},
			},
			["self"] = {
				["Skin"] = 0,
				["UniqueID"] = "f33977e9741ffbb474d991595f28638f4ad91f7e7a3f5d362a83ecb0e1a0030e",
				["NoLighting"] = false,
				["AimPartName"] = "",
				["IgnoreZ"] = false,
				["AimPartUID"] = "",
				["Materials"] = "",
				["Name"] = "",
				["LevelOfDetail"] = 0,
				["NoTextureFiltering"] = false,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["EyeAngles"] = false,
				["DrawOrder"] = 0,
				["TargetEntityUID"] = "",
				["Alpha"] = 1,
				["Material"] = "",
				["Invert"] = false,
				["ForceObjUrl"] = false,
				["Bone"] = "head",
				["Angles"] = Angle(0, 0, 0),
				["AngleOffset"] = Angle(0, 0, 0),
				["BoneMerge"] = true,
				["Color"] = Vector(1, 1, 1),
				["Position"] = Vector(-0.14111328125, 0.0009765625, 0),
				["ClassName"] = "model2",
				["Brightness"] = 1,
				["Hide"] = false,
				["NoCulling"] = false,
				["Scale"] = Vector(1, 1, 1),
				["LegacyTransform"] = false,
				["EditorExpand"] = false,
				["Size"] = 1,
				["ModelModifiers"] = "",
				["Translucent"] = false,
				["BlendMode"] = "",
				["EyeTargetUID"] = "",
				["Model"] = "models/tnb/techcom/female_68.mdl",
			},
		},
		[2] = {
			["children"] = {
				[1] = {
					["children"] = {
					},
					["self"] = {
						["DrawOrder"] = 0,
						["UniqueID"] = "0c7ba95d34f52e668c78111ed4c614320d925fe97569095cf735e9ef6bc864cc",
						["Hide"] = false,
						["TargetEntityUID"] = "",
						["EditorExpand"] = false,
						["Name"] = "",
						["Material"] = "pp/frame_blend",
						["IsDisturbing"] = false,
						["SubMaterialId"] = 3,
						["ClassName"] = "submaterial",
						["RootOwner"] = false,
					},
				},
				[2] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["InvertHideMesh"] = false,
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right bicep",
						["ScaleChildren"] = false,
						["UniqueID"] = "085573c3a12aa9be43ea0d70ac0b03586413218dfeba2f12cabfb807368a1fa9",
						["MoveChildrenToOrigin"] = false,
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Angles"] = Angle(0, 0, 0),
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["ClassName"] = "bone3",
						["Size"] = 0.9,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[3] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["InvertHideMesh"] = false,
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left bicep",
						["ScaleChildren"] = false,
						["UniqueID"] = "4bb466d97f71ca148dfdfc4231eeb89e9c955c8e670d4f3b447a9588ff7a825f",
						["MoveChildrenToOrigin"] = false,
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Angles"] = Angle(0, 0, 0),
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["ClassName"] = "bone3",
						["Size"] = 0.9,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[4] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["InvertHideMesh"] = false,
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left upperarm",
						["ScaleChildren"] = false,
						["UniqueID"] = "719f28da2b5557c2e15ff855646ea392af8f5bce56a17ad0f265e06a2f4e7ce3",
						["MoveChildrenToOrigin"] = false,
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Angles"] = Angle(0, 0, 0),
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["ClassName"] = "bone3",
						["Size"] = 0.9,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[5] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["InvertHideMesh"] = false,
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right upperarm",
						["ScaleChildren"] = false,
						["UniqueID"] = "093b964828acc44df8a4f744a92d6527992efa3bc06f993c5fc65b1203fda6bf",
						["MoveChildrenToOrigin"] = false,
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Angles"] = Angle(0, 0, 0),
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["ClassName"] = "bone3",
						["Size"] = 0.9,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[6] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["InvertHideMesh"] = false,
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left ulna",
						["ScaleChildren"] = false,
						["UniqueID"] = "499ad32d0418ee2d9f1010dbcf4670800c24b4773d6d38d31d6061acab39dc4f",
						["MoveChildrenToOrigin"] = false,
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Angles"] = Angle(0, 0, 0),
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["ClassName"] = "bone3",
						["Size"] = 0.9,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[7] = {
					["children"] = {
					},
					["self"] = {
						["DrawOrder"] = 0,
						["UniqueID"] = "ce5efc3783bde88321b94be1ca0afbab49e25788c62fadc31d5ccd463beae273",
						["Hide"] = false,
						["TargetEntityUID"] = "",
						["EditorExpand"] = false,
						["Name"] = "",
						["Material"] = "pp/frame_blend",
						["IsDisturbing"] = false,
						["SubMaterialId"] = 2,
						["ClassName"] = "submaterial",
						["RootOwner"] = false,
					},
				},
				[8] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["InvertHideMesh"] = false,
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right ulna",
						["ScaleChildren"] = false,
						["UniqueID"] = "31dc869747b7ad38f62b8d0c892b5adf651305c3a50f78e54cb83a0bfa1f6ade",
						["MoveChildrenToOrigin"] = false,
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Angles"] = Angle(0, 0, 0),
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["ClassName"] = "bone3",
						["Size"] = 0.9,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[9] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["InvertHideMesh"] = false,
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "spine 1",
						["ScaleChildren"] = false,
						["UniqueID"] = "2f08a0985dc8de9ae20478428b7cfeb26c9e9f167ca44e445c05a18ed3dd856e",
						["MoveChildrenToOrigin"] = false,
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Angles"] = Angle(0, 0, 0),
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["ClassName"] = "bone3",
						["Size"] = 0.9,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[10] = {
					["children"] = {
						[1] = {
							["children"] = {
							},
							["self"] = {
								["DrawOrder"] = 0,
								["UniqueID"] = "b7cc254325f8aebb6216001d46f9b20e89c662277bfbfc41b3b669afc408bd05",
								["TargetEntityUID"] = "",
								["AimPartName"] = "",
								["Bone"] = "head",
								["BlendMode"] = "",
								["Position"] = Vector(-2.2939453125, 6.103515625e-05, -0.001953125),
								["AimPartUID"] = "",
								["NoTextureFiltering"] = false,
								["Hide"] = false,
								["Name"] = "",
								["Translucent"] = false,
								["IgnoreZ"] = false,
								["Angles"] = Angle(0, 0, 0),
								["AngleOffset"] = Angle(0, 0, 0),
								["PositionOffset"] = Vector(0, 0, 0),
								["IsDisturbing"] = false,
								["ClassName"] = "clip2",
								["EyeAngles"] = false,
								["EditorExpand"] = false,
							},
						},
					},
					["self"] = {
						["Skin"] = 0,
						["UniqueID"] = "4fce2d31337636f86b6c3f54a73813d2341b0f337634550ff96b72940cc33c3a",
						["NoLighting"] = false,
						["AimPartName"] = "",
						["IgnoreZ"] = false,
						["AimPartUID"] = "",
						["Materials"] = "",
						["Name"] = "",
						["LevelOfDetail"] = 0,
						["NoTextureFiltering"] = false,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["EyeAngles"] = false,
						["DrawOrder"] = 0,
						["TargetEntityUID"] = "",
						["Alpha"] = 1,
						["Material"] = "",
						["Invert"] = false,
						["ForceObjUrl"] = false,
						["Bone"] = "pelvis",
						["Angles"] = Angle(-43.76057434082, -177.81185913086, -7.6422547863331e-06),
						["AngleOffset"] = Angle(0, 0, 0),
						["BoneMerge"] = false,
						["Color"] = Vector(1, 1, 1),
						["Position"] = Vector(4.47265625, 2.2645111083984, 3.8740234375),
						["ClassName"] = "model2",
						["Brightness"] = 1,
						["Hide"] = false,
						["NoCulling"] = false,
						["Scale"] = Vector(1, 1, 2.2999999523163),
						["LegacyTransform"] = false,
						["EditorExpand"] = false,
						["Size"] = 0.4,
						["ModelModifiers"] = "",
						["Translucent"] = false,
						["BlendMode"] = "",
						["EyeTargetUID"] = "",
						["Model"] = "models/illusion/eftcontainers/docbag.mdl",
					},
				},
				[11] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["InvertHideMesh"] = false,
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right wrist",
						["ScaleChildren"] = false,
						["UniqueID"] = "57cdffe839b7731621807fa1840556476b7493c1a692caeab8296dd349c1cd24",
						["MoveChildrenToOrigin"] = false,
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Angles"] = Angle(0, 0, 0),
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["ClassName"] = "bone3",
						["Size"] = 0.9,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[12] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["InvertHideMesh"] = false,
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left wrist",
						["ScaleChildren"] = false,
						["UniqueID"] = "179f437e54f2632b3c8ca0795bc71e5212d5c62d34a2e3355de5603082544e5c",
						["MoveChildrenToOrigin"] = false,
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Angles"] = Angle(0, 0, 0),
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["ClassName"] = "bone3",
						["Size"] = 0.9,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[13] = {
					["children"] = {
						[1] = {
							["children"] = {
							},
							["self"] = {
								["DrawOrder"] = 0,
								["UniqueID"] = "d0fad9d15f5b3465bf90f415c02a0bd1fd21c9386070edde3a747b654fae3e25",
								["TargetEntityUID"] = "",
								["AimPartName"] = "",
								["Bone"] = "head",
								["BlendMode"] = "",
								["Position"] = Vector(2.1123046875, -0.00048828125, 4.3364591598511),
								["AimPartUID"] = "",
								["NoTextureFiltering"] = false,
								["Hide"] = false,
								["Name"] = "",
								["Translucent"] = false,
								["IgnoreZ"] = false,
								["Angles"] = Angle(75.26286315918, -119.21812438965, -120.04174041748),
								["AngleOffset"] = Angle(0, 0, 0),
								["PositionOffset"] = Vector(0, 0, 0),
								["IsDisturbing"] = false,
								["ClassName"] = "clip2",
								["EyeAngles"] = false,
								["EditorExpand"] = false,
							},
						},
						[2] = {
							["children"] = {
							},
							["self"] = {
								["DrawOrder"] = 0,
								["UniqueID"] = "4f6161b356a08ac3515f5c9a56f11728135a547e50e344906433cb3bb0a1580c",
								["TargetEntityUID"] = "",
								["AimPartName"] = "",
								["Bone"] = "head",
								["BlendMode"] = "",
								["Position"] = Vector(2.1123046875, -0.00048828125, 4.3364591598511),
								["AimPartUID"] = "",
								["NoTextureFiltering"] = false,
								["Hide"] = false,
								["Name"] = "",
								["Translucent"] = false,
								["IgnoreZ"] = false,
								["Angles"] = Angle(77.861228942871, 2.4107264835038e-05, -1.0150427442568e-05),
								["AngleOffset"] = Angle(0, 0, 0),
								["PositionOffset"] = Vector(0, 0, 0),
								["IsDisturbing"] = false,
								["ClassName"] = "clip2",
								["EyeAngles"] = false,
								["EditorExpand"] = false,
							},
						},
						[3] = {
							["children"] = {
							},
							["self"] = {
								["DrawOrder"] = 0,
								["UniqueID"] = "9e8c9b920a78950c49c6b9ea1356e8ff2d75e75cd3f4ce589588bc8408bd4f40",
								["TargetEntityUID"] = "",
								["AimPartName"] = "",
								["Bone"] = "head",
								["BlendMode"] = "",
								["Position"] = Vector(2.1123046875, -0.00048828125, 4.3364591598511),
								["AimPartUID"] = "",
								["NoTextureFiltering"] = false,
								["Hide"] = false,
								["Name"] = "",
								["Translucent"] = false,
								["IgnoreZ"] = false,
								["Angles"] = Angle(72.85432434082, -45.798721313477, -44.496570587158),
								["AngleOffset"] = Angle(0, 0, 0),
								["PositionOffset"] = Vector(0, 0, 0),
								["IsDisturbing"] = false,
								["ClassName"] = "clip2",
								["EyeAngles"] = false,
								["EditorExpand"] = false,
							},
						},
						[4] = {
							["children"] = {
							},
							["self"] = {
								["DrawOrder"] = 0,
								["UniqueID"] = "461381275f287695af073d6f393c8e3b4d391e3bd278fc6751917ba4e6b630c1",
								["TargetEntityUID"] = "",
								["AimPartName"] = "",
								["Bone"] = "head",
								["BlendMode"] = "",
								["Position"] = Vector(2.1123046875, -0.00048828125, 4.3364591598511),
								["AimPartUID"] = "",
								["NoTextureFiltering"] = false,
								["Hide"] = false,
								["Name"] = "",
								["Translucent"] = false,
								["IgnoreZ"] = false,
								["Angles"] = Angle(74.120971679688, 118.39894104004, 119.2479019165),
								["AngleOffset"] = Angle(0, 0, 0),
								["PositionOffset"] = Vector(0, 0, 0),
								["IsDisturbing"] = false,
								["ClassName"] = "clip2",
								["EyeAngles"] = false,
								["EditorExpand"] = false,
							},
						},
						[5] = {
							["children"] = {
							},
							["self"] = {
								["DrawOrder"] = 0,
								["UniqueID"] = "7db4717dcc3939da81dab00c832e735cc14d002664d7086cac324f55f0744910",
								["TargetEntityUID"] = "",
								["AimPartName"] = "",
								["Bone"] = "head",
								["BlendMode"] = "",
								["Position"] = Vector(2.087890625, -0.047119140625, 3.8904161453247),
								["AimPartUID"] = "",
								["NoTextureFiltering"] = false,
								["Hide"] = false,
								["Name"] = "",
								["Translucent"] = false,
								["IgnoreZ"] = false,
								["Angles"] = Angle(80.581985473633, -109.90483856201, -108.51876068115),
								["AngleOffset"] = Angle(0, 0, 0),
								["PositionOffset"] = Vector(0, 0, 0),
								["IsDisturbing"] = false,
								["ClassName"] = "clip2",
								["EyeAngles"] = false,
								["EditorExpand"] = false,
							},
						},
						[6] = {
							["children"] = {
							},
							["self"] = {
								["DrawOrder"] = 0,
								["UniqueID"] = "bc63951322c71a7affe1d4f61dcc3ba278d6864523bf0123a33366586ac437ee",
								["TargetEntityUID"] = "",
								["AimPartName"] = "",
								["Bone"] = "head",
								["BlendMode"] = "",
								["Position"] = Vector(2.1123046875, -0.00048828125, 4.3364591598511),
								["AimPartUID"] = "",
								["NoTextureFiltering"] = false,
								["Hide"] = false,
								["Name"] = "",
								["Translucent"] = false,
								["IgnoreZ"] = false,
								["Angles"] = Angle(75.3447265625, 68.251564025879, 70.660209655762),
								["AngleOffset"] = Angle(0, 0, 0),
								["PositionOffset"] = Vector(0, 0, 0),
								["IsDisturbing"] = false,
								["ClassName"] = "clip2",
								["EyeAngles"] = false,
								["EditorExpand"] = false,
							},
						},
						[7] = {
							["children"] = {
							},
							["self"] = {
								["DrawOrder"] = 0,
								["UniqueID"] = "376087d990718fea0abf6c7621094dae9e044ff8db5718ec3525ec61207aa82f",
								["TargetEntityUID"] = "",
								["AimPartName"] = "",
								["Bone"] = "head",
								["BlendMode"] = "",
								["Position"] = Vector(2.3671875, -0.68701171875, 6.3103685379028),
								["AimPartUID"] = "",
								["NoTextureFiltering"] = false,
								["Hide"] = false,
								["Name"] = "",
								["Translucent"] = false,
								["IgnoreZ"] = false,
								["Angles"] = Angle(43.798885345459, 97.072525024414, 100.16274261475),
								["AngleOffset"] = Angle(0, 0, 0),
								["PositionOffset"] = Vector(0, 0, 0),
								["IsDisturbing"] = false,
								["ClassName"] = "clip2",
								["EyeAngles"] = false,
								["EditorExpand"] = false,
							},
						},
					},
					["self"] = {
						["Skin"] = 0,
						["UniqueID"] = "2d0df988eba7c57c4d092f426a0f6b1601e764284775edbb2f57cebbc7b66b06",
						["NoLighting"] = false,
						["AimPartName"] = "",
						["IgnoreZ"] = false,
						["AimPartUID"] = "",
						["Materials"] = "",
						["Name"] = "",
						["LevelOfDetail"] = 0,
						["NoTextureFiltering"] = false,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["EyeAngles"] = false,
						["DrawOrder"] = 0,
						["TargetEntityUID"] = "",
						["Alpha"] = 1,
						["Material"] = "",
						["Invert"] = false,
						["ForceObjUrl"] = false,
						["Bone"] = "eyes",
						["Angles"] = Angle(0, 0, 0),
						["AngleOffset"] = Angle(0, 0, 0),
						["BoneMerge"] = false,
						["Color"] = Vector(0.14509804546833, 0.14509804546833, 0.14509804546833),
						["Position"] = Vector(-3.154296875, 0, -1.0961575508118),
						["ClassName"] = "model2",
						["Brightness"] = 1,
						["Hide"] = false,
						["NoCulling"] = false,
						["Scale"] = Vector(1, 1, 1),
						["LegacyTransform"] = false,
						["EditorExpand"] = false,
						["Size"] = 0.9,
						["ModelModifiers"] = "",
						["Translucent"] = false,
						["BlendMode"] = "",
						["EyeTargetUID"] = "",
						["Model"] = "models/mosi/fallout4/character/male/malehair06.mdl",
					},
				},
				[14] = {
					["children"] = {
						[1] = {
							["children"] = {
							},
							["self"] = {
								["FollowAnglesOnly"] = false,
								["DrawOrder"] = 0,
								["InvertHideMesh"] = false,
								["TargetEntityUID"] = "",
								["AimPartName"] = "",
								["FollowPartUID"] = "",
								["Bone"] = "head",
								["ScaleChildren"] = false,
								["UniqueID"] = "7cc164d73d3c0d10508932d0e642b7992c124827a10296d33663aeea2e17930a",
								["MoveChildrenToOrigin"] = false,
								["Position"] = Vector(0.94580000638962, 0.28549998998642, -0.00019999999494758),
								["AimPartUID"] = "",
								["Angles"] = Angle(0, 0, 0),
								["Hide"] = false,
								["Name"] = "",
								["Scale"] = Vector(1, 1, 1),
								["EditorExpand"] = false,
								["ClassName"] = "bone3",
								["Size"] = 0.925,
								["PositionOffset"] = Vector(0, 0, 0),
								["IsDisturbing"] = false,
								["AngleOffset"] = Angle(0, 0, 0),
								["EyeAngles"] = false,
								["HideMesh"] = false,
							},
						},
					},
					["self"] = {
						["Skin"] = 0,
						["UniqueID"] = "fc6da4863e71b9f77444590cf03dac7a34e574433f374f8920910872efb8fe2e",
						["NoLighting"] = false,
						["AimPartName"] = "",
						["IgnoreZ"] = false,
						["AimPartUID"] = "",
						["Materials"] = "",
						["Name"] = "",
						["LevelOfDetail"] = 0,
						["NoTextureFiltering"] = false,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["EyeAngles"] = false,
						["DrawOrder"] = 0,
						["TargetEntityUID"] = "",
						["Alpha"] = 1,
						["Material"] = "",
						["Invert"] = false,
						["ForceObjUrl"] = false,
						["Bone"] = "head",
						["Angles"] = Angle(-1.2766356468201, -77.549461364746, -90.281845092773),
						["AngleOffset"] = Angle(0, 0, 0),
						["BoneMerge"] = false,
						["Color"] = Vector(1, 1, 1),
						["Position"] = Vector(-62.528900146484, -15.210900306702, 0.313232421875),
						["ClassName"] = "model2",
						["Brightness"] = 1,
						["Hide"] = false,
						["NoCulling"] = false,
						["Scale"] = Vector(0.89999997615814, 1, 1),
						["LegacyTransform"] = false,
						["EditorExpand"] = false,
						["Size"] = 1,
						["ModelModifiers"] = "",
						["Translucent"] = false,
						["BlendMode"] = "",
						["EyeTargetUID"] = "",
						["Model"] = "models/shtokerbox/headgear/male_mask_arab.mdl",
					},
				},
				[15] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["InvertHideMesh"] = false,
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left calf",
						["ScaleChildren"] = false,
						["UniqueID"] = "0c60db38a14d956e37fed2fbb04e84bb8db515d1535b4e907c3780afbe7b92d4",
						["MoveChildrenToOrigin"] = false,
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Angles"] = Angle(0, 0, 0),
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["ClassName"] = "bone3",
						["Size"] = 0.875,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[16] = {
					["children"] = {
					},
					["self"] = {
						["DrawOrder"] = 0,
						["UniqueID"] = "45f6a76c1b6e42f5c2aecb43436cd5f69009867b0cdf2953b74f2bf57b71146d",
						["Hide"] = false,
						["TargetEntityUID"] = "",
						["EditorExpand"] = false,
						["Name"] = "",
						["Material"] = "pp/frame_blend",
						["IsDisturbing"] = false,
						["SubMaterialId"] = 1,
						["ClassName"] = "submaterial",
						["RootOwner"] = false,
					},
				},
				[17] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["InvertHideMesh"] = false,
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "left shoulder",
						["ScaleChildren"] = false,
						["UniqueID"] = "80f06f0ee8586dadc2895179c088932c2c29009f4eff9fc775af957b1a7e75f7",
						["MoveChildrenToOrigin"] = false,
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Angles"] = Angle(0, 0, 0),
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["ClassName"] = "bone3",
						["Size"] = 0.9,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[18] = {
					["children"] = {
					},
					["self"] = {
						["Skin"] = 0,
						["UniqueID"] = "5503869ab91fb4ac2c732f0aad557f5987155514ff9c8793ab35f2a437c04135",
						["NoLighting"] = false,
						["AimPartName"] = "",
						["IgnoreZ"] = false,
						["AimPartUID"] = "",
						["Materials"] = "",
						["Name"] = "",
						["LevelOfDetail"] = 0,
						["NoTextureFiltering"] = false,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["EyeAngles"] = false,
						["DrawOrder"] = 0,
						["TargetEntityUID"] = "",
						["Alpha"] = 1,
						["Material"] = "",
						["Invert"] = false,
						["ForceObjUrl"] = false,
						["Bone"] = "pelvis",
						["Angles"] = Angle(-71.277778625488, 38.457317352295, 55.602390289307),
						["AngleOffset"] = Angle(0, 0, 0),
						["BoneMerge"] = false,
						["Color"] = Vector(1, 1, 1),
						["Position"] = Vector(2.493408203125, 5.6774439811707, 5.529296875),
						["ClassName"] = "model2",
						["Brightness"] = 1,
						["Hide"] = false,
						["NoCulling"] = false,
						["Scale"] = Vector(1, 1, 1),
						["LegacyTransform"] = false,
						["EditorExpand"] = false,
						["Size"] = 0.625,
						["ModelModifiers"] = "",
						["Translucent"] = false,
						["BlendMode"] = "",
						["EyeTargetUID"] = "",
						["Model"] = "models/mosi/fallout4/props/junk/magnifyingglass.mdl",
					},
				},
				[19] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["InvertHideMesh"] = false,
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "pelvis",
						["ScaleChildren"] = false,
						["UniqueID"] = "8730bf01159a844f5c1bbdf803d55de765b7d87fbe6cef4f460b8386c7deb168",
						["MoveChildrenToOrigin"] = false,
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Angles"] = Angle(0, 0, 0),
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(0.89999997615814, 1, 0.89999997615814),
						["EditorExpand"] = false,
						["ClassName"] = "bone3",
						["Size"] = 1,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[20] = {
					["children"] = {
						[1] = {
							["children"] = {
							},
							["self"] = {
								["DrawOrder"] = 0,
								["UniqueID"] = "1166368439",
								["Hide"] = false,
								["TargetEntityUID"] = "",
								["EditorExpand"] = false,
								["Name"] = "",
								["Material"] = "pp/frame_blend",
								["IsDisturbing"] = false,
								["SubMaterialId"] = 8,
								["ClassName"] = "submaterial",
								["RootOwner"] = false,
							},
						},
						[2] = {
							["children"] = {
							},
							["self"] = {
								["DrawOrder"] = 0,
								["UniqueID"] = "3968877260",
								["Hide"] = false,
								["TargetEntityUID"] = "",
								["EditorExpand"] = false,
								["Name"] = "",
								["Material"] = "pp/frame_blend",
								["IsDisturbing"] = false,
								["SubMaterialId"] = 9,
								["ClassName"] = "submaterial",
								["RootOwner"] = false,
							},
						},
						[3] = {
							["children"] = {
							},
							["self"] = {
								["DrawOrder"] = 0,
								["UniqueID"] = "3836764792",
								["Hide"] = false,
								["TargetEntityUID"] = "",
								["EditorExpand"] = false,
								["Name"] = "",
								["Material"] = "pp/frame_blend",
								["IsDisturbing"] = false,
								["SubMaterialId"] = 2,
								["ClassName"] = "submaterial",
								["RootOwner"] = false,
							},
						},
						[4] = {
							["children"] = {
							},
							["self"] = {
								["DrawOrder"] = 0,
								["UniqueID"] = "2193619974",
								["Hide"] = false,
								["TargetEntityUID"] = "",
								["EditorExpand"] = false,
								["Name"] = "",
								["Material"] = "pp/frame_blend",
								["IsDisturbing"] = false,
								["SubMaterialId"] = 3,
								["ClassName"] = "submaterial",
								["RootOwner"] = false,
							},
						},
						[5] = {
							["children"] = {
							},
							["self"] = {
								["DrawOrder"] = 0,
								["UniqueID"] = "2809905174",
								["Hide"] = false,
								["TargetEntityUID"] = "",
								["EditorExpand"] = false,
								["Name"] = "",
								["Material"] = "pp/frame_blend",
								["IsDisturbing"] = false,
								["SubMaterialId"] = 1,
								["ClassName"] = "submaterial",
								["RootOwner"] = false,
							},
						},
						[6] = {
							["children"] = {
							},
							["self"] = {
								["DrawOrder"] = 0,
								["UniqueID"] = "1491627949",
								["Hide"] = false,
								["TargetEntityUID"] = "",
								["EditorExpand"] = false,
								["Name"] = "",
								["Material"] = "pp/frame_blend",
								["IsDisturbing"] = false,
								["SubMaterialId"] = 5,
								["ClassName"] = "submaterial",
								["RootOwner"] = false,
							},
						},
						[7] = {
							["children"] = {
							},
							["self"] = {
								["DrawOrder"] = 0,
								["UniqueID"] = "3013319317",
								["Hide"] = false,
								["TargetEntityUID"] = "",
								["EditorExpand"] = false,
								["Name"] = "",
								["Material"] = "pp/frame_blend",
								["IsDisturbing"] = false,
								["SubMaterialId"] = 4,
								["ClassName"] = "submaterial",
								["RootOwner"] = false,
							},
						},
						[8] = {
							["children"] = {
							},
							["self"] = {
								["DrawOrder"] = 0,
								["UniqueID"] = "2128019304",
								["Hide"] = false,
								["TargetEntityUID"] = "",
								["EditorExpand"] = false,
								["Name"] = "",
								["Material"] = "pp/frame_blend",
								["IsDisturbing"] = false,
								["SubMaterialId"] = 9,
								["ClassName"] = "submaterial",
								["RootOwner"] = false,
							},
						},
					},
					["self"] = {
						["Skin"] = 0,
						["UniqueID"] = "1239842568",
						["NoLighting"] = false,
						["AimPartName"] = "",
						["IgnoreZ"] = false,
						["AimPartUID"] = "",
						["Materials"] = "",
						["Name"] = "",
						["LevelOfDetail"] = 0,
						["NoTextureFiltering"] = false,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["EyeAngles"] = false,
						["DrawOrder"] = 0,
						["TargetEntityUID"] = "",
						["Alpha"] = 1,
						["Material"] = "",
						["Invert"] = false,
						["ForceObjUrl"] = false,
						["Bone"] = "eyes",
						["Angles"] = Angle(0, 0, 0),
						["AngleOffset"] = Angle(0, 0, 0),
						["BoneMerge"] = false,
						["Color"] = Vector(1, 1, 1),
						["Position"] = Vector(-4.252299785614, 0.014899999834597, -65.516296386719),
						["ClassName"] = "model2",
						["Brightness"] = 1,
						["Hide"] = false,
						["NoCulling"] = false,
						["Scale"] = Vector(1, 1, 1),
						["LegacyTransform"] = false,
						["EditorExpand"] = false,
						["Size"] = 1.0000000238419,
						["ModelModifiers"] = "",
						["Translucent"] = false,
						["BlendMode"] = "",
						["EyeTargetUID"] = "",
						["Model"] = "https://www.dropbox.com/s/z3d28qwtj5aeqem/readingglasses.zip?dl=1",
					},
				},
				[21] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["InvertHideMesh"] = false,
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right forearm",
						["ScaleChildren"] = false,
						["UniqueID"] = "aaa84ca4c2ccffc89799ee8b335bd136ce5d15fcd918f9638673e0329921c918",
						["MoveChildrenToOrigin"] = false,
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Angles"] = Angle(0, 0, 0),
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["ClassName"] = "bone3",
						["Size"] = 0.9,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[22] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["InvertHideMesh"] = false,
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "spine 2",
						["ScaleChildren"] = false,
						["UniqueID"] = "3b2424fafdb4ea5e515ef9fb00f13892ce81c1bb5cf79017999f66efead41bb7",
						["MoveChildrenToOrigin"] = false,
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Angles"] = Angle(0, 0, 0),
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["ClassName"] = "bone3",
						["Size"] = 0.9,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[23] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["InvertHideMesh"] = false,
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "spine",
						["ScaleChildren"] = false,
						["UniqueID"] = "6de8d4d431082d30476c023388ebcb79b1f5f476616f2b937e464fc955f746ee",
						["MoveChildrenToOrigin"] = false,
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Angles"] = Angle(0, 0, 0),
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["ClassName"] = "bone3",
						["Size"] = 0.9,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[24] = {
					["children"] = {
					},
					["self"] = {
						["Skin"] = 0,
						["UniqueID"] = "590b7958b37fdbb82c97785d7849b182f0d91980bbdfc02e9a5f2182f217efdf",
						["NoLighting"] = false,
						["AimPartName"] = "",
						["IgnoreZ"] = false,
						["AimPartUID"] = "",
						["Materials"] = "",
						["Name"] = "",
						["LevelOfDetail"] = 0,
						["NoTextureFiltering"] = false,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["EyeAngles"] = false,
						["DrawOrder"] = 0,
						["TargetEntityUID"] = "",
						["Alpha"] = 1,
						["Material"] = "",
						["Invert"] = false,
						["ForceObjUrl"] = false,
						["Bone"] = "eyes",
						["Angles"] = Angle(0, 0, 0),
						["AngleOffset"] = Angle(0, 0, 0),
						["BoneMerge"] = false,
						["Color"] = Vector(1, 1, 1),
						["Position"] = Vector(-4.0571999549866, 0, -57.636199951172),
						["ClassName"] = "model2",
						["Brightness"] = 1,
						["Hide"] = false,
						["NoCulling"] = false,
						["Scale"] = Vector(1, 1, 1),
						["LegacyTransform"] = false,
						["EditorExpand"] = false,
						["Size"] = 0.875,
						["ModelModifiers"] = "",
						["Translucent"] = false,
						["BlendMode"] = "",
						["EyeTargetUID"] = "",
						["Model"] = "models/shtokerbox/headgear/male_headwear_boonie1.mdl",
					},
				},
				[25] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["InvertHideMesh"] = false,
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right shoulder",
						["ScaleChildren"] = false,
						["UniqueID"] = "e9b34ec6ebf9d344216b85f17282b009cf8a985305060c4d96a1c3b10e4ce70f",
						["MoveChildrenToOrigin"] = false,
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Angles"] = Angle(0, 0, 0),
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["ClassName"] = "bone3",
						["Size"] = 0.9,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[26] = {
					["children"] = {
					},
					["self"] = {
						["Skin"] = 1,
						["UniqueID"] = "71c9c53c9146e043a4f2beedb47ae82a16dc02ebecf80b6f3502b1968c8a74fc",
						["NoLighting"] = false,
						["AimPartName"] = "",
						["IgnoreZ"] = false,
						["AimPartUID"] = "",
						["Materials"] = "",
						["Name"] = "",
						["LevelOfDetail"] = 0,
						["NoTextureFiltering"] = false,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["EyeAngles"] = false,
						["DrawOrder"] = 0,
						["TargetEntityUID"] = "",
						["Alpha"] = 1,
						["Material"] = "",
						["Invert"] = false,
						["ForceObjUrl"] = false,
						["Bone"] = "spine 2",
						["Angles"] = Angle(-87.184272766113, -66.768089294434, 156.79316711426),
						["AngleOffset"] = Angle(0, 0, 0),
						["BoneMerge"] = false,
						["Color"] = Vector(1, 1, 1),
						["Position"] = Vector(12.104583740234, 44.2392578125, 1.76513671875),
						["ClassName"] = "model2",
						["Brightness"] = 1,
						["Hide"] = false,
						["NoCulling"] = false,
						["Scale"] = Vector(0.89999997615814, 0.89999997615814, 1),
						["LegacyTransform"] = false,
						["EditorExpand"] = false,
						["Size"] = 1,
						["ModelModifiers"] = "",
						["Translucent"] = false,
						["BlendMode"] = "",
						["EyeTargetUID"] = "",
						["Model"] = "models/shtokerbox/ground_backpack_rucksack.mdl",
					},
				},
				[27] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["InvertHideMesh"] = false,
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right calf",
						["ScaleChildren"] = false,
						["UniqueID"] = "2f71424b8ef2c01fce2b9fe49fe99211ff0d08995df6110ae03d9f52552f840c",
						["MoveChildrenToOrigin"] = false,
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Angles"] = Angle(0, 0, 0),
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["ClassName"] = "bone3",
						["Size"] = 0.875,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
			},
			["self"] = {
				["Skin"] = 0,
				["UniqueID"] = "19304eb52523362b3be8794ba68d9ab2f7afcc6659383a405bc41ddf3575650e",
				["NoLighting"] = false,
				["AimPartName"] = "",
				["IgnoreZ"] = false,
				["AimPartUID"] = "",
				["Materials"] = "",
				["Name"] = "",
				["LevelOfDetail"] = 0,
				["NoTextureFiltering"] = false,
				["PositionOffset"] = Vector(0, 0, 0),
				["IsDisturbing"] = false,
				["EyeAngles"] = false,
				["DrawOrder"] = 0,
				["TargetEntityUID"] = "",
				["Alpha"] = 1,
				["Material"] = "",
				["Invert"] = false,
				["ForceObjUrl"] = false,
				["Bone"] = "head",
				["Angles"] = Angle(0, 0, 0),
				["AngleOffset"] = Angle(0, 0, 0),
				["BoneMerge"] = true,
				["Color"] = Vector(1, 1, 1),
				["Position"] = Vector(0, 0, 0),
				["ClassName"] = "model2",
				["Brightness"] = 1,
				["Hide"] = false,
				["NoCulling"] = false,
				["Scale"] = Vector(1, 1, 1),
				["LegacyTransform"] = false,
				["EditorExpand"] = true,
				["Size"] = 1,
				["ModelModifiers"] = "gasmasks=0;head_frills=0;",
				["Translucent"] = false,
				["BlendMode"] = "",
				["EyeTargetUID"] = "",
				["Model"] = "https://www.dropbox.com/s/wf75ipmdn9z7din/stalkerclothes.zip?dl=1",
			},
		},
		[3] = {
			["children"] = {
				[1] = {
					["children"] = {
					},
					["self"] = {
						["FollowAnglesOnly"] = false,
						["DrawOrder"] = 0,
						["InvertHideMesh"] = false,
						["TargetEntityUID"] = "",
						["AimPartName"] = "",
						["FollowPartUID"] = "",
						["Bone"] = "right finger 1",
						["ScaleChildren"] = false,
						["UniqueID"] = "59063f88c580dc4c4c232bc73645436c8ffabca445ceb9543729c187522fb108",
						["MoveChildrenToOrigin"] = false,
						["Position"] = Vector(0, 0, 0),
						["AimPartUID"] = "",
						["Angles"] = Angle(0, 0, 0),
						["Hide"] = false,
						["Name"] = "",
						["Scale"] = Vector(1, 1, 1),
						["EditorExpand"] = false,
						["ClassName"] = "bone3",
						["Size"] = 1,
						["PositionOffset"] = Vector(-1, 0.10000000149012, 0.10000000149012),
						["IsDisturbing"] = false,
						["AngleOffset"] = Angle(0, 0, 0),
						["EyeAngles"] = false,
						["HideMesh"] = false,
					},
				},
				[2] = {
					["children"] = {
					},
					["self"] = {
						["Skin"] = 0,
						["UniqueID"] = "ac95c4e0a762217d5fb1251b4471641177a44e843ecc5e62b5b1db999c0ffb87",
						["NoLighting"] = false,
						["AimPartName"] = "",
						["IgnoreZ"] = false,
						["AimPartUID"] = "",
						["Materials"] = "",
						["Name"] = "Gun",
						["LevelOfDetail"] = 0,
						["NoTextureFiltering"] = false,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["EyeAngles"] = false,
						["DrawOrder"] = 0,
						["TargetEntityUID"] = "",
						["Alpha"] = 1,
						["Material"] = "",
						["Invert"] = false,
						["ForceObjUrl"] = false,
						["Bone"] = "right hand",
						["Angles"] = Angle(-6.2907028198242, 179.99993896484, 180),
						["AngleOffset"] = Angle(0, 0, 0),
						["BoneMerge"] = false,
						["Color"] = Vector(1, 1, 1),
						["Position"] = Vector(5.6055908203125, -1.7197265625, -3.9724731445313),
						["ClassName"] = "model2",
						["Brightness"] = 1,
						["Hide"] = false,
						["NoCulling"] = false,
						["Scale"] = Vector(1, 1, 1),
						["LegacyTransform"] = false,
						["EditorExpand"] = false,
						["Size"] = 0.8,
						["ModelModifiers"] = "",
						["Translucent"] = false,
						["BlendMode"] = "",
						["EyeTargetUID"] = "",
						["Model"] = "models/tnb/weapons/w_38.mdl",
					},
				},
			},
			["self"] = {
				["AffectChildrenOnly"] = true,
				["DrawOrder"] = 0,
				["TargetPartUID"] = "",
				["Name"] = "",
				["Event"] = "weapon_class",
				["Hide"] = false,
				["TargetEntityUID"] = "",
				["RootOwner"] = true,
				["EditorExpand"] = false,
				["ClassName"] = "event",
				["Arguments"] = "m10@@1",
				["Invert"] = true,
				["IsDisturbing"] = false,
				["Operator"] = "find simple",
				["UniqueID"] = "07626c8e7cd0b41b546485f11a388f2b9bfbf46ef9d0e8a64dd190df41c774be",
				["ZeroEyePitch"] = false,
			},
		},
		[4] = {
			["children"] = {
				[1] = {
					["children"] = {
						[1] = {
							["children"] = {
							},
							["self"] = {
								["FollowAnglesOnly"] = false,
								["DrawOrder"] = 0,
								["InvertHideMesh"] = false,
								["TargetEntityUID"] = "",
								["AimPartName"] = "",
								["FollowPartUID"] = "",
								["Bone"] = "left hand",
								["ScaleChildren"] = false,
								["UniqueID"] = "b42f536de525864c7fc11636d7773ec94ffc4e6f00df9a3dac2294bbc9d40fd8",
								["MoveChildrenToOrigin"] = false,
								["Position"] = Vector(0, 0, 0),
								["AimPartUID"] = "",
								["Angles"] = Angle(-3.6250319480896, 0.59055197238922, 113.93141937256),
								["Hide"] = false,
								["Name"] = "",
								["Scale"] = Vector(1, 1, 1),
								["EditorExpand"] = false,
								["ClassName"] = "bone3",
								["Size"] = 1,
								["PositionOffset"] = Vector(0, 0, 0),
								["IsDisturbing"] = false,
								["AngleOffset"] = Angle(0, 0, 0),
								["EyeAngles"] = false,
								["HideMesh"] = false,
							},
						},
						[2] = {
							["children"] = {
							},
							["self"] = {
								["FollowAnglesOnly"] = false,
								["DrawOrder"] = 0,
								["InvertHideMesh"] = false,
								["TargetEntityUID"] = "",
								["AimPartName"] = "",
								["FollowPartUID"] = "",
								["Bone"] = "right hand",
								["ScaleChildren"] = false,
								["UniqueID"] = "7bfba47b191921db33655eb77f0524920981dbe77111fd9c748573ba1d121465",
								["MoveChildrenToOrigin"] = false,
								["Position"] = Vector(0, 0, 0),
								["AimPartUID"] = "",
								["Angles"] = Angle(11.189172744751, 15.803985595703, 0.76358497142792),
								["Hide"] = false,
								["Name"] = "",
								["Scale"] = Vector(1, 1, 1),
								["EditorExpand"] = false,
								["ClassName"] = "bone3",
								["Size"] = 1,
								["PositionOffset"] = Vector(0, 0, 0),
								["IsDisturbing"] = false,
								["AngleOffset"] = Angle(0, 0, 0),
								["EyeAngles"] = false,
								["HideMesh"] = false,
							},
						},
						[3] = {
							["children"] = {
							},
							["self"] = {
								["FollowAnglesOnly"] = false,
								["DrawOrder"] = 0,
								["InvertHideMesh"] = false,
								["TargetEntityUID"] = "",
								["AimPartName"] = "",
								["FollowPartUID"] = "",
								["Bone"] = "right forearm",
								["ScaleChildren"] = false,
								["UniqueID"] = "d366e94b59fc43e61746111487ab6434f57225cf2a29c8c27086a1df212cd3f5",
								["MoveChildrenToOrigin"] = false,
								["Position"] = Vector(0, 0, 0),
								["AimPartUID"] = "",
								["Angles"] = Angle(-8.5683374404907, 69.371170043945, 36.711280822754),
								["Hide"] = false,
								["Name"] = "",
								["Scale"] = Vector(1, 1, 1),
								["EditorExpand"] = false,
								["ClassName"] = "bone3",
								["Size"] = 1,
								["PositionOffset"] = Vector(0, 0, 0),
								["IsDisturbing"] = false,
								["AngleOffset"] = Angle(0, 0, 0),
								["EyeAngles"] = false,
								["HideMesh"] = false,
							},
						},
						[4] = {
							["children"] = {
							},
							["self"] = {
								["FollowAnglesOnly"] = false,
								["DrawOrder"] = 0,
								["InvertHideMesh"] = false,
								["TargetEntityUID"] = "",
								["AimPartName"] = "",
								["FollowPartUID"] = "",
								["Bone"] = "right forearm",
								["ScaleChildren"] = false,
								["UniqueID"] = "41d1de8d1c27a958539927136715104f3054db86d016f782f8e597e29857be2d",
								["MoveChildrenToOrigin"] = false,
								["Position"] = Vector(0, 0, 0),
								["AimPartUID"] = "",
								["Angles"] = Angle(4.2562613487244, 8.5613481815017e-07, -1.4126220776234e-05),
								["Hide"] = false,
								["Name"] = "",
								["Scale"] = Vector(1, 1, 1),
								["EditorExpand"] = false,
								["ClassName"] = "bone3",
								["Size"] = 1,
								["PositionOffset"] = Vector(0, 0, 0),
								["IsDisturbing"] = false,
								["AngleOffset"] = Angle(0, 0, 0),
								["EyeAngles"] = false,
								["HideMesh"] = false,
							},
						},
						[5] = {
							["children"] = {
							},
							["self"] = {
								["FollowAnglesOnly"] = false,
								["DrawOrder"] = 0,
								["InvertHideMesh"] = false,
								["TargetEntityUID"] = "",
								["AimPartName"] = "",
								["FollowPartUID"] = "",
								["Bone"] = "left finger 01",
								["ScaleChildren"] = false,
								["UniqueID"] = "eff7a26160c5487481f1a2bef861b2d79caa50f1716f89a4bb14f804b588720f",
								["MoveChildrenToOrigin"] = false,
								["Position"] = Vector(0, 0, 0),
								["AimPartUID"] = "",
								["Angles"] = Angle(64.843704223633, -179.99998474121, 180),
								["Hide"] = false,
								["Name"] = "",
								["Scale"] = Vector(1, 1, 1),
								["EditorExpand"] = false,
								["ClassName"] = "bone3",
								["Size"] = 1,
								["PositionOffset"] = Vector(0, 0, 0),
								["IsDisturbing"] = false,
								["AngleOffset"] = Angle(0, 0, 0),
								["EyeAngles"] = false,
								["HideMesh"] = false,
							},
						},
						[6] = {
							["children"] = {
							},
							["self"] = {
								["FollowAnglesOnly"] = false,
								["DrawOrder"] = 0,
								["InvertHideMesh"] = false,
								["TargetEntityUID"] = "",
								["AimPartName"] = "",
								["FollowPartUID"] = "",
								["Bone"] = "left forearm",
								["ScaleChildren"] = false,
								["UniqueID"] = "dc9b901fda86abab1fc59d10d9ffb697093421d91b9e40079592f2de4f0b6732",
								["MoveChildrenToOrigin"] = false,
								["Position"] = Vector(0, 0, 0),
								["AimPartUID"] = "",
								["Angles"] = Angle(10.704078674316, 45.645393371582, 2.8673466658802e-05),
								["Hide"] = false,
								["Name"] = "",
								["Scale"] = Vector(1, 1, 1),
								["EditorExpand"] = false,
								["ClassName"] = "bone3",
								["Size"] = 1,
								["PositionOffset"] = Vector(0, 0, 0),
								["IsDisturbing"] = false,
								["AngleOffset"] = Angle(0, 0, 0),
								["EyeAngles"] = false,
								["HideMesh"] = false,
							},
						},
					},
					["self"] = {
						["AffectChildrenOnly"] = true,
						["DrawOrder"] = 0,
						["TargetPartUID"] = "",
						["Name"] = "",
						["Event"] = "sequence_name",
						["Hide"] = false,
						["TargetEntityUID"] = "",
						["RootOwner"] = true,
						["EditorExpand"] = true,
						["ClassName"] = "event",
						["Arguments"] = "passive",
						["Invert"] = true,
						["IsDisturbing"] = false,
						["Operator"] = "find simple",
						["UniqueID"] = "90fa96aaab77c94c4227e03884017ffbc7d43a638c4c2fd0e7825b166d47731b",
						["ZeroEyePitch"] = false,
					},
				},
			},
			["self"] = {
				["AffectChildrenOnly"] = true,
				["DrawOrder"] = 0,
				["TargetPartUID"] = "",
				["Name"] = "",
				["Event"] = "weapon_class",
				["Hide"] = false,
				["TargetEntityUID"] = "",
				["RootOwner"] = true,
				["EditorExpand"] = false,
				["ClassName"] = "event",
				["Arguments"] = "m10@@1",
				["Invert"] = true,
				["IsDisturbing"] = false,
				["Operator"] = "find simple",
				["UniqueID"] = "4552052008431ac489b97385d7c933dfcdd5b23d493827fbfde10a2086ddde7a",
				["ZeroEyePitch"] = false,
			},
		},
		[5] = {
			["children"] = {
			},
			["self"] = {
				["Skin"] = 0,
				["UniqueID"] = "e2b812eb6a934df233ffc232ca85ea2d2eb13f423cb0a788cb1e030c4106fa69",
				["NoLighting"] = false,
				["BlendMode"] = "",
				["AimPartUID"] = "",
				["Materials"] = "",
				["Name"] = "",
				["LevelOfDetail"] = 0,
				["NoTextureFiltering"] = false,
				["InverseKinematics"] = true,
				["PositionOffset"] = Vector(0, 0, 0),
				["NoCulling"] = false,
				["Brightness"] = 1,
				["DrawOrder"] = 0,
				["TargetEntityUID"] = "",
				["DrawShadow"] = true,
				["Alpha"] = 1,
				["Material"] = "",
				["CrouchingHullHeight"] = 36,
				["Model"] = "",
				["ModelModifiers"] = "",
				["NoDraw"] = true,
				["IgnoreZ"] = false,
				["HullWidth"] = 32,
				["Translucent"] = false,
				["Position"] = Vector(0, 0, 0),
				["LegacyTransform"] = false,
				["ClassName"] = "entity2",
				["Hide"] = false,
				["IsDisturbing"] = false,
				["Scale"] = Vector(1, 1, 1),
				["Color"] = Vector(1, 1, 1),
				["EditorExpand"] = false,
				["Size"] = 0.975,
				["Invert"] = false,
				["Angles"] = Angle(0, 0, 0),
				["AngleOffset"] = Angle(0, 0, 0),
				["EyeTargetUID"] = "",
				["StandingHullHeight"] = 72,
			},
		},
	},
	["self"] = {
		["DrawOrder"] = 0,
		["UniqueID"] = "ef3d7a53bd59a0fd4e394feceb0354f2ad3e68521170eb124ffb4e36a05be25d",
		["Hide"] = false,
		["TargetEntityUID"] = "",
		["EditorExpand"] = true,
		["OwnerName"] = "self",
		["IsDisturbing"] = false,
		["Name"] = "my outfit",
		["Duplicate"] = false,
		["ClassName"] = "group",
	},
},
[2] = {
	["children"] = {
		[1] = {
			["children"] = {
				[1] = {
					["children"] = {
					},
					["self"] = {
						["DrawOrder"] = 0,
						["UniqueID"] = "67cd13a85720cfb49f159c296f7944d25e9a24d5a4799fe28d04f41d7c39c1fb",
						["SequenceName"] = "",
						["InvertFrames"] = false,
						["WeaponHoldType"] = "pistol",
						["Offset"] = 0,
						["ResetOnHide"] = true,
						["Max"] = 1,
						["Hide"] = false,
						["Min"] = 0,
						["Loop"] = true,
						["Name"] = "",
						["EditorExpand"] = false,
						["PingPongLoop"] = false,
						["Rate"] = 1,
						["IsDisturbing"] = false,
						["OwnerCycle"] = false,
						["ClassName"] = "animation",
						["TargetEntityUID"] = "",
					},
				},
				[2] = {
					["children"] = {
					},
					["self"] = {
						["Skin"] = 0,
						["UniqueID"] = "f495bad266ad901d973dd8601bdbef7f727f4e97290b6fd26db169c972a2f7d7",
						["NoLighting"] = false,
						["AimPartName"] = "",
						["IgnoreZ"] = false,
						["AimPartUID"] = "",
						["Materials"] = "",
						["Name"] = "",
						["LevelOfDetail"] = 0,
						["NoTextureFiltering"] = false,
						["PositionOffset"] = Vector(0, 0, 0),
						["IsDisturbing"] = false,
						["EyeAngles"] = false,
						["DrawOrder"] = 0,
						["TargetEntityUID"] = "",
						["Alpha"] = 1,
						["Material"] = "",
						["Invert"] = false,
						["ForceObjUrl"] = false,
						["Bone"] = "right hand",
						["Angles"] = Angle(66.196647644043, 28.678184509277, -153.41384887695),
						["AngleOffset"] = Angle(0, 0, 0),
						["BoneMerge"] = false,
						["Color"] = Vector(1, 1, 1),
						["Position"] = Vector(3.78466796875, -2.3777008056641, -2.6082763671875),
						["ClassName"] = "model2",
						["Brightness"] = 1,
						["Hide"] = false,
						["NoCulling"] = false,
						["Scale"] = Vector(1, 1, 1),
						["LegacyTransform"] = false,
						["EditorExpand"] = false,
						["Size"] = 1,
						["ModelModifiers"] = "Switch 1=1;Switch 2=1;Switch 3=1;Button=1;Cover=1;",
						["Translucent"] = false,
						["BlendMode"] = "",
						["EyeTargetUID"] = "",
						["Model"] = "models/kali/miscstuff/stalker/detector_echo.mdl",
					},
				},
			},
			["self"] = {
				["AffectChildrenOnly"] = true,
				["DrawOrder"] = 0,
				["TargetPartUID"] = "",
				["Name"] = "",
				["Event"] = "weapon_class",
				["Hide"] = false,
				["TargetEntityUID"] = "",
				["RootOwner"] = true,
				["EditorExpand"] = true,
				["ClassName"] = "event",
				["Arguments"] = "echo@@1",
				["Invert"] = true,
				["IsDisturbing"] = false,
				["Operator"] = "find simple",
				["UniqueID"] = "5e97cf67a29de4c8026807d0465c090a5244933841b3a7e8b49c26ca87a0b38e",
				["ZeroEyePitch"] = false,
			},
		},
	},
	["self"] = {
		["DrawOrder"] = 0,
		["UniqueID"] = "babe22be12849089476f85c242cb619706ea47a4519010bbbb7b273569693c9f",
		["Hide"] = false,
		["TargetEntityUID"] = "",
		["EditorExpand"] = true,
		["OwnerName"] = "self",
		["IsDisturbing"] = false,
		["Name"] = "",
		["Duplicate"] = false,
		["ClassName"] = "group",
	},
},
}